### ISSUE TITLE
corners surrounding vertex broken

### ISSUE THREAD

**Issue by wohlbier** [flecsi/flecsi#16]
There is a problem with corners surrounding a vertex. To reproduce, update to the latest version of
src/specializations/burton/test/burton.cc
and look at the output from the last test. The first vertex reports that it has all of the corners, and it has corner 0 twice. The output you should see is below. The corner ids for all other vertices seem reasonable.

corners_for_vertices

vertex: 0
corner: 0
corner: 0
corner: 1
corner: 2
corner: 3
corner: 4
corner: 5
corner: 6
corner: 7
corner: 8
corner: 9
corner: 10
corner: 11
corner: 12
corner: 13
corner: 14
corner: 15

vertex: 1
corner: 1
corner: 4

vertex: 2
corner: 5

vertex: 3
corner: 3
corner: 8

vertex: 4
corner: 2
corner: 7
corner: 9
corner: 12

vertex: 5
corner: 6
corner: 13

vertex: 6
corner: 11

vertex: 7
corner: 10
corner: 15

vertex: 8
corner: 14

**Comment by charest** [comment]
How do the wedges look?  Because corners don't exist in mesh topology, only wedges do

**Comment by nickm319** [comment]
I just fixed this, just about to push it. create bound entities was wrong in burton types.

**Comment by wohlbier** [comment]
Sweet!

**Comment by nickm319** [comment]
Fixed definition of create_bound_entities() in burton entity types.
