### ISSUE TITLE
burton_gradients segfaults

### ISSUE THREAD

**Issue by charest** [flecsi/flecsi#17]
Segfaults when run with all other tests, but works fine when run individually

**Comment by nickm319** [comment]
This sounds familiar to another problem we were having a while back. Have you tried running Valgrind on it?

**Comment by wohlbier** [comment]
It was more benign than that. I used to have to have a relative path in the file name for writing a mesh out of a test, but Ben's cinch change fixed that. Just had to remove "test/" from the file name.
