### ISSUE TITLE
Separate "early" and "late" prolog in HPX backend

### ISSUE THREAD

**Issue by hkaiser** [flecsi/flecsi#2]
The need for an "early" and "late" prolog is actually found in the Legion backend as well (and per our analysis might be expected to apply to an upgraded MPI backend that actually ran tasks in parallel).  There it is realized not as two prologs but as a prolog and `bind_accessors`, the latter of which does not have access to the arguments (because it might be running in a different memory space!) but rather has some backend-specific **encoding** of their contents (beyond that captured in the serialization).

I think that strategy could apply here, in particular by storing the `region_impl*` needed by each accessor in the initial prolog pass and a flag to control the broadcast of `global` data.  This would have the significant advantage that there would be no need to pass (copies of) the arguments around (but rather the summary just described) and the minor advantage that we would not need to make `exec::prolog` a template.

_Originally posted by @opensdh in https://github.com/flecsi/flecsi/pull/1#discussion_r793082555_

**Comment by opensdh** [comment]
This was done in #1 after all (since there was plenty of time for it).
