### ISSUE TITLE
Flexi in Flecsi

### ISSUE THREAD

**Issue by ollielo** [flecsi/flecsi#2]
There are several references to flexi in the current flecsi code base.

> driver/flecsi-serial.cc:#include <flexi/utils/common.h>
> driver/flecsi-serial.cc:  return flexi::execution_t<>::execute_task(driver, argc, argv);
> examples/01_simple_task/types.h:#include <flexi/specializations/burton/burton.h>
> examples/01_simple_task/types.h:#include <flexi/execution/task.h>
> examples/01_simple_task/types.h:using burton_mesh_t = flexi::burton_mesh_t;
> examples/01_simple_task/types.h:using flexi::persistent;

Interesting enough, they are not caught by any test suites because the executables are not built.

**Comment by tuxfan** [comment]
Thanks Ollie!  I'm getting rid of them now...

**Comment by ollielo** [comment]
In additional to changing flexi to flecsi, can you also make sure flecsi-serial.cc and 01_simple_task are built? I am not so familiar with the build system.

**Comment by tuxfan** [comment]
I'm sort of working on that.  Right now, you have to use the flecsi script to do it (and I think that there is a compiler bug).  If you want to try the serial version, just do (in your build directory):

% bin/flecsi ../examples/00_hello_world/hello_world.h

This should build an executable.  The same should work for the simple_task example.  Just send another message if it doesn't work and I will try to figure it out with you...

**Comment by tuxfan** [comment]
Hold off on that.  It looks like I have something screwed up.  I'll let you know when I get it to work again...

**Comment by tuxfan** [comment]
Ok.  This should work now.  There was actually another FLEXI reference even after I went through them.  I just compiled the two examples.  I'll start working on building them as executables as part of the normal build (without having to use the script).  I'm going to leave the script in place as an easy way to play with new input decks.  Please try to update your repo and build the examples in the way that I described above...

**Comment by tuxfan** [comment]
I think that I got all of the flexi references.  Closing this issue...

**Comment by ollielo** [comment]
I can build hello_world.h but not script-driver-mpi.cc

Is it correct to use

> ollie@salami Build]$ ./bin/flecsi ../driver/script-driver-mpi.cc 

to built it? It caused hundreds lines of error message and stop at

> script-driver-mpi.cc:29:5: note: ‘int main(int, char**)’ previously defined here
>  int main(int argc, char ** argv) {
>      ^
> /home/ollie/git/flecsi/Build/share/script-driver-serial.cc:29:46: error: ‘driver’ was not declared in this scope
>    return flecsi::execution_t<>::execute_task(driver, argc, argv);

**Comment by tuxfan** [comment]
No.  You would have to reconfigure your build to use 'mpi' for the FLECSI_RUTNIME_MODEL option, rebuild, and then you might be able to build.  The '.cc' files are not valid drivers for flecsi, they are part of the underlying configuration, e.g., the serial driver is the default.

- Ben

-
Dr.-Ing. Benjamin Karl Bergen, M.Sc.
Los Alamos National Laboratory
P.O. Box 1663, MS B287
Los Alamos, NM 87545

505-795-2275 (c)
505-667-1699 (w)
