### ISSUE TITLE
Issues with the cmake version of legion

### ISSUE THREAD

**Issue by spad12** [flecsi/flecsi#21]
The following header files are not in the install directory for legion:
* lowlevel_config.h
* realm/realm_config.h (basically any realm header)
* common.h
* accessor.h
* arrays.h
etc...

also from the legion/runtime/legion directory
* legion_constraint.h

Basically it looks like any header file in the legion/runtime directory is not included.

**Comment by ipdemes** [comment]
I've pushed the fix for that to the legion cmake branch on Monday. There is one more design issue I've found trying to use crake-built-legion in flecsi that I am working on right now. I'l push the fix for that to flecsi and legion today.

**Comment by spad12** [comment]
Excellent, thanks Irina

**Comment by ipdemes** [comment]
I've just pushed fixes to the Legion's cmake branch and to flecsi. Please let me know if you still have any issues.
P.S. a am going to implement legion execution policy in cinch now
