### ISSUE TITLE
MPI-enable build is broken

### ISSUE THREAD

**Issue by junghans** [flecsi/flecsi#25]
Using `-DENABLE_MPI=ON` fails:
https://travis-ci.org/junghans/flecsi/jobs/112658215

```
CMake Error at CMakeLists.txt:599 (add_test):
  add_test given unknown argument:

    mpi



-- Configuring incomplete, errors occurred!
```

**Comment by ollielo** [comment]
I tried to look into it when I got bored in the meeting. However, my laptop
is too old to meet the requirements, starting from the version of CMake. I
will looking into when I am back to the office.

Ollie

**Comment by ollielo** [comment]
This is actually a cinch problem:

diff --git a/cmake/ProjectLists.txt b/cmake/ProjectLists.txt
index 2a8fdc1..da5b930 100644
--- a/cmake/ProjectLists.txt
+++ b/cmake/ProjectLists.txt
@@ -606,7 +606,6 @@ if(${CINCH_TOP_LEVEL_PROJECT})
                 if(NOT "${unit_policy_exec}" STREQUAL "None")
                     add_test(
                         NAME
-                            ${unit_target_name}
                             "${_TEST_PREFIX}${unit_target_name}"
                         COMMAND
                             ${unit_policy_exec}

**Comment by ollielo** [comment]
I mean, remove line 607 with

${unit_target_name}
