### ISSUE TITLE
Cannot clone repository

### ISSUE THREAD

**Issue by charest** [flecsi/flecsi#3]
**Cloning using https link fails:**

git clone --recursive https://github.com/flecsi/flecsi.git
Initialized empty Git repository in /local/home/charest/flecsi/.git/
remote: Counting objects: 3722, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 3722 (delta 57), reused 0 (delta 0), pack-reused 3610
Receiving objects: 100% (3722/3722), 1.24 MiB | 1.59 MiB/s, done.
Resolving deltas: 100% (2568/2568), done.
Submodule 'cinch' (git@github.com:losalamos/cinch.git) registered for path 'cinch'
Initialized empty Git repository in /local/home/charest/flecsi/cinch/.git/
remote: Counting objects: 1426, done.
remote: Compressing objects: 100% (536/536), done.
remote: Total 1426 (delta 848), reused 1420 (delta 842), pack-reused 0
Receiving objects: 100% (1426/1426), 1.22 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (848/848), done.
Submodule path 'cinch': checked out '9798489475ba49cdd38eb91663fa0e6044ae11ce'
Submodule 'gtest' (git@github.com:losalamos/google/googletest.git) registered for path 'gtest'
Initialized empty Git repository in /local/home/charest/flecsi/cinch/gtest/.git/
fatal: remote error: 
  losalamos/google/googletest is not a valid repository name
  Email support@github.com for help
Clone of 'git@github.com:losalamos/google/googletest.git' into submodule path 'gtest' faile

**Cloning using ssh link fails:**

git clone --recursive git@github.com:flecsi/flecsi.git
Initialized empty Git repository in /local/home/charest/flecsi/.git/
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
remote: Counting objects: 3722, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 3722 (delta 57), reused 0 (delta 0), pack-reused 3610
Receiving objects: 100% (3722/3722), 1.24 MiB, done.
Resolving deltas: 100% (2568/2568), done.
Submodule 'cinch' (git@github.com:losalamos/cinch.git) registered for path 'cinch'
Initialized empty Git repository in /local/home/charest/flecsi/cinch/.git/
remote: Counting objects: 1426, done.
remote: Compressing objects: 100% (536/536), done.
remote: Total 1426 (delta 848), reused 1420 (delta 842), pack-reused 0
Receiving objects: 100% (1426/1426), 1.22 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (848/848), done.
Submodule path 'cinch': checked out '9798489475ba49cdd38eb91663fa0e6044ae11ce'
Submodule 'gtest' (git@github.com:losalamos/google/googletest.git) registered for path 'gtest'
Initialized empty Git repository in /local/home/charest/flecsi/cinch/gtest/.git/
fatal: remote error: 
  losalamos/google/googletest is not a valid repository name
  Email support@github.com for help
Clone of 'git@github.com:losalamos/google/googletest.git' into submodule path 'gtest' failed
Failed to recurse into submodule path 'cinch

**Comment by charest** [comment]
Only happens for old versions of git.  This was for git version 1.7.1, which is ancient.

**Comment by tuxfan** [comment]
Good.  I was worried for a second.  It seems like it could be an issue for someone because it looks like git uses the git@github thing for submodules even if the parent has been checked out with https...

**Comment by charest** [comment]
**I got someone without a git account to try, they get this error**

remote: Counting objects: 3722, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 3722 (delta 57), reused 0 (delta 0), pack-reused 3610
Receiving objects: 100% (3722/3722), 1.24 MiB | 964 KiB/s, done.
Resolving deltas: 100% (2568/2568), done.
Submodule 'cinch' (git@github.com:losalamos/cinch.git) registered for
path 'cinch'
Initialized empty Git repository in /local/starrett/tmp/flecsi/cinch/.git/
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list
of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:losalamos/cinch.git' into submodule path
'cinch' faile

**Comment by tuxfan** [comment]
I think that I have a fix for this.  Could you try to clone it again?

**Comment by charest** [comment]
**Works now**

Initialized empty Git repository in /local/starrett/tmp/flecsi/.git/
remote: Counting objects: 3724, done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 3724 (delta 58), reused 0 (delta 0), pack-reused 3610
Receiving objects: 100% (3724/3724), 1.24 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (2569/2569), done.
Submodule 'cinch' (https://github.com/losalamos/cinch.git) registered for path 'cinch'
Initialized empty Git repository in /local/starrett/tmp/flecsi/cinch/.git/
remote: Counting objects: 1426, done.
remote: Compressing objects: 100% (536/536), done.
remote: Total 1426 (delta 848), reused 1420 (delta 842), pack-reused 0
Receiving objects: 100% (1426/1426), 1.22 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (848/848), done.
Submodule path 'cinch': checked out '9798489475ba49cdd38eb91663fa0e6044ae11ce'
Submodule 'gtest' (https://github.com/google/googletest.git) registered for path 'gtest'
Initialized empty Git repository in /local/starrett/tmp/flecsi/cinch/gtest/.git/
remote: Counting objects: 7174, done.
remote: Total 7174 (delta 0), reused 0 (delta 0), pack-reused 7174
Receiving objects: 100% (7174/7174), 2.50 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (5344/5344), done.
Submodule path 'gtest': checked out 'ff5ffd457e032c8be8a64a7a94c824063c8b11e3'
